// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back.Data;

#nullable disable

namespace back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("back.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Diversas camisas para hombre y mujer.",
                            Nombre = "Camisas"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Pantalones, jeans y chinos para todas las ocasiones.",
                            Nombre = "Pantalones"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Chaquetas de cuero, lana, y más para todo tipo de clima.",
                            Nombre = "Chaquetas"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Sombreros y gorras para el sol y el estilo.",
                            Nombre = "Sombreros"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Zapatos y calzado de cuero, deportivos, casuales y formales.",
                            Nombre = "Zapatos"
                        });
                });

            modelBuilder.Entity("back.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Camisa básica de algodón para hombre, talla M.",
                            Nombre = "Camisa de algodón",
                            Precio = 25.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descripcion = "Pantalones de mezclilla, corte regular, color azul.",
                            Nombre = "Pantalones de mezclilla",
                            Precio = 49.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Descripcion = "Chaqueta de cuero genuino, estilo moto, color negro.",
                            Nombre = "Chaqueta de cuero",
                            Precio = 120.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            Descripcion = "Sombrero de paja para el verano, color beige.",
                            Nombre = "Sombrero de paja",
                            Precio = 19.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 5,
                            Descripcion = "Zapatos de cuero para hombre, color marrón, talla 42.",
                            Nombre = "Zapatos de cuero",
                            Precio = 89.99m
                        });
                });

            modelBuilder.Entity("back.Models.Producto", b =>
                {
                    b.HasOne("back.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("back.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
